name: FurfSky Upgrader

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
      file_name:
        description: 'Name to save the file as'
        required: true
        default: 'furfsky_1.21.x.zip'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Download the file
      - name: Download file
        run: |
          wget ${{ github.event.inputs.file_url }}

      # Upload the file as an artifact
      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.file_name }}
          path: ./${{ github.event.inputs.file_name }}
